#! /bin/bash

#	AUTOSTART
sxhkd &
nitrogen --restore &
polybar -r --config=$HOME/.config/polybar/config.ini example &
picom &
xsetroot -cursor_name left_ptr &
setxkbmap -option grp:win_space_toggle us,ru &
xinput --set-prop 9 315 1 &
xset r rate 250 40 &
nm-applet --indicator &
dunst &

#numlockx &

#	WORKSPACES
bspc monitor -d        


#	GAPS & BORDERS
bspc config border_width        2
bspc config window_gap          8

bspc config normal_border_color "#181926"
bspc config active_border_color "#181926"
bspc config focused_border_color "#1A73E8"

#	COLOR PRESET OF NEW APP BG
bspc config presel_feedback_color "fd2e59"

#	GAPS BETWEEN WINDOWS
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))



#	PERCENT OF SPACE AFTER OPEN A WINDOW
bspc config split_ratio          0.5

#	WINDOW FOCUS BY MOUSE CURSOR
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#	MONOCLE WHEN A SINGLE WINDOW IS OPEN
bspc config single_monocle	     false

	#TURNING OFF GAPS & OUTLINES WHEN A SINGLE WINDOW IS OPENED
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

#	WINDOWS OPEN STYLE
#bspc config automatic_scheme	spiral


#	WINDOWS RULES
#bspc rule -a firefox state=floating follow=off rectangle=1350x900+50+90 desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
#bspc rule -a Steam state=floating follow=off rectangle=1350x900+285+90 desktop='^6' 
#bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
#bspc rule -a dmenu rectangle=900x22+610+90
#bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
#bspc rule -a Inkscape desktop='^3'
#bspc rule -a Blender desktop='^2'

